GET http://localhost:3003/api/blogs HTTP/1.1

 
###
GET http://localhost:3003/api/blogs/66ab53f7b968ecbca16e822d HTTP/1.1

 
###
GET http://localhost:3003/api/blogs/66a673f7b968ecbca16e822d HTTP/1.1

###
GET http://localhost:3003/api/blogs/66a673f7 68ecbca16e822d HTTP/1.1