
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "la bala que doblo la esquina",
    "author": "Elon Muserterk",
    "url":"htttp:/sdfdsf",
    "likes":1
}
