
###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "root",
    "name": "superuser",
    "password": "root"
}
###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "usuario1",
    "name": "uno dos tres",
    "password": "usuario1"
}
###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "usuario3",
    "name": "dos tres cuatro",
    "password": "usuario3"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/login/ HTTP/1.1
content-type: application/json

{
    "username": "usuario3", 
    "password": "usuario3"
}
